<a href="https://colab.research.google.com/github/lucianapopa/Python_Data_Analysis_Event_Alura/blob/main/Class_01_Alura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CLASS 01

In [ ]:
import pandas as pd

# Library used for data analysis.

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

# 'pd' is used to retrieve the library for database reading.

# If a link is included on the code it must be between quotes.

In [ ]:
df.head()

# This command is used in order to visualize the data inside the file.

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [ ]:
# It is possible to see that the data is organized, but it suggests that improvements must be done to enhance data
# analysis and further visualization.

# The data presents information on employeers seniority, job title, salary, location, work location, among other data.

# Analysis regarding the relationship between experience level and salary accross different job sectors might be valuable
# when analysing which job has higher salaries,or even in comparison with other metrics for example analysing salaries
# with a company's revenue.

In [ ]:
df.info()

# To obtain general information about the database.

# We can observe the columns, quantity of information, if there is null values or not, and the data type.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [ ]:
df.describe()

# To visualize descriptive statistic data.

# Utilizes numeric values.

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [ ]:
df.shape

# Since it is an attribute instead of method or function parenthesis is not used.

# Tuples and columns quantities are displayed.

(133349, 11)

In [ ]:
lines, columns = df.shape[0], df.shape[1]

print("Lines:", lines)
print("Columns:", columns)

Lines: 133349
Columns: 11

In [ ]:
df.columns

# We can see all the columns' names at once.

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [ ]:
df = df.rename(columns={
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
})

display(df.head())

# As part of the practice, I've changed the column names from English to Brazilian Portuguese.

# If I decide to rename columns again, the previous line must be previously runned.

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [ ]:
df["senioridade"].value_counts()

# Verifying each category frequency within the 'experience level' column.

# It is possible to see that the majority of analysed employees are seniors.

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [ ]:
df["contrato"].value_counts()

# Employment contrat frequency: full-time, contract, part-time, freelancer.

# The majority of contracts are full-time.

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [ ]:
df["remoto"].value_counts()

# 0 = presencial/ on-site
# 50 = remoto/ remote
# 100 = hibridas/ hybrid

# The majority of employees work on-site.

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [ ]:
df["tamanho_empresa"].value_counts()

# The majority of companies are medium-sized.

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [ ]:
# Renaming the categories within the columns replacing abbreviations for full terms for better understanding.

In [ ]:
senioridade = {
    'SE': 'Senior',
    'MI': 'Pleno',
    'EN': 'Junior',
    'EX': 'Especialista'
}

df['senioridade'] = df['senioridade'].replace(senioridade)

display(df.head())

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,Senior,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,Pleno,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,Pleno,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,Junior,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [ ]:
contrato = {
    'FT': 'Full-time',
    'CT': 'Contract',
    'PT': 'Part-time',
    'FL': 'Freelancer'
}

df['contrato'] = df['contrato'].replace(contrato)

display(df.head())

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Full-time,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,Senior,Full-time,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,Pleno,Full-time,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,Pleno,Full-time,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,Junior,Full-time,Data Engineer,90000,USD,90000,US,0,US,M

In [ ]:
tamanho_empresa = {
    'S': 'Startup',
    'M': 'Médio',
    'L': 'Grande'
}

df['tamanho_empresa'] = df['tamanho_empresa'].replace(tamanho_empresa)

display(df.head())

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Full-time,Solutions Engineer,214000,USD,214000,US,100,US,Médio
1,2025.0,Senior,Full-time,Solutions Engineer,136000,USD,136000,US,100,US,Médio
2,2025.0,Pleno,Full-time,Data Engineer,158800,USD,158800,AU,0,AU,Médio
3,2025.0,Pleno,Full-time,Data Engineer,139200,USD,139200,AU,0,AU,Médio
4,2025.0,Junior,Full-time,Data Engineer,90000,USD,90000,US,0,US,Médio

In [ ]:
remoto = {
    0: 'Presencial',
    50: 'Remoto',
    100: 'Híbrido'
}

df['remoto'] = df['remoto'].replace(remoto)

display(df.head())

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Full-time,Solutions Engineer,214000,USD,214000,US,Híbrido,US,Médio
1,2025.0,Senior,Full-time,Solutions Engineer,136000,USD,136000,US,Híbrido,US,Médio
2,2025.0,Pleno,Full-time,Data Engineer,158800,USD,158800,AU,Presencial,AU,Médio
3,2025.0,Pleno,Full-time,Data Engineer,139200,USD,139200,AU,Presencial,AU,Médio
4,2025.0,Junior,Full-time,Data Engineer,90000,USD,90000,US,Presencial,US,Médio

In [ ]:
df.head()

# Now, the categories are well defined as well as the columns, streamlining the understanding of the data.

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Full-time,Solutions Engineer,214000,USD,214000,US,Híbrido,US,Médio
1,2025.0,Senior,Full-time,Solutions Engineer,136000,USD,136000,US,Híbrido,US,Médio
2,2025.0,Pleno,Full-time,Data Engineer,158800,USD,158800,AU,Presencial,AU,Médio
3,2025.0,Pleno,Full-time,Data Engineer,139200,USD,139200,AU,Presencial,AU,Médio
4,2025.0,Junior,Full-time,Data Engineer,90000,USD,90000,US,Presencial,US,Médio

In [ ]:
df.describe(include = "object")

# General information on the categorical variables.

# Here we have:
# Count: how many values we have on a column,
# Unique: unique values within each column,
# Top: most frequent information within each column,
# Freq: how many time the most frequent value appears on each column.

,senioridade,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Senior,Full-time,Data Scientist,USD,US,Presencial,US,Médio
freq,77241,132563,17314,126140,119579,105312,119641,129561

In [ ]:
df.describe()

# General data on categorical data.

# There is over 100,000 analysed data.

# For statistical purposes all the metrics present on the table are extremelly useful such as central tendency
# measures, quartiles and min/max values.

                 ano       salario            usd
count  133339.000000  1.333490e+05  133349.000000
mean     2024.358770  1.632833e+05  157617.272098
std         0.680627  2.173860e+05   74288.363097
min      2020.000000  1.400000e+04   15000.000000
25%      2024.000000  1.060200e+05  106000.000000
50%      2024.000000  1.470000e+05  146206.000000
75%      2025.000000  1.990000e+05  198000.000000
max      2025.000000  3.040000e+07  800000.000000